deps: update black code formatter
Bumped due to an issue while linting code:
> error: cannot format `kodiak/queries/__init__.py`: INTERNAL ERROR
> Black produced code that is not equivalent to the source.